name: Rust tests
on:
  push: null
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    - name: Check Rita and Rita Exit x86
      run: cargo check --all
      id: _bre_check
    - uses: Swatinem/rust-cache@v2
    - name: Run Rita and Rita Exit tests
      run: cargo test --verbose --all
      id: _bre_test
    - name: Check code formatting
      run: rustup component add rustfmt && cargo fmt --all -- --check
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Check for Clippy lints
      run: rustup component add clippy && cargo clippy --all --all-targets --all-features -- -D warnings
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run Cargo Audit
      run: cargo install cargo-audit && cargo audit
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run integration test
      run: bash scripts/integration_tests/all-up-test-ci.sh FIVE_NODES
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run integration test
      run: bash scripts/integration_tests/all-up-test-ci.sh PAYMENTS_ALTHEA
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run integration test
      run: bash scripts/integration_tests/all-up-test-ci.sh DEBTS_TEST
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run integration test
      run: bash scripts/integration_tests/all-up-test-ci.sh ETH_PAYMENTS
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run integration test
      run: bash scripts/integration_tests/all-up-test-ci.sh MULTI_EXIT
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run integration test
      run: bash scripts/integration_tests/all-up-test-ci.sh CONTRACT_TEST
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run integration test
      run: bash scripts/integration_tests/all-up-test-ci.sh SNAT_EXIT
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - name: Run integration test
      run: bash scripts/integration_tests/all-up-test-ci.sh CGNAT_EXIT
      if: '!cancelled() && steps._bre_check.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      if: '!cancelled() && steps._bre_test.conclusion == ''success'''
    - name: Cross test aarch64
      run: cargo install cross && cross build --target aarch64-unknown-linux-musl --verbose -p rita_bin
        --bin rita
      if: '!cancelled() && steps._bre_test.conclusion == ''success'''
    - uses: Swatinem/rust-cache@v2
      if: '!cancelled() && steps._bre_test.conclusion == ''success'''
    - name: Cross test armv7
      run: cargo install cross && cross build --target armv7-unknown-linux-musleabihf --verbose -p rita_bin
        --bin rita
      if: '!cancelled() && steps._bre_test.conclusion == ''success'''
